fragment author on User {
  name
  id
}

fragment post on Post {
  id
  title
  text
  author {
    ...author
  }
}

query postList {
  postList {
    ...post
  }
}

mutation deletePost($id: Int!) {
  deletePost(id: $id)
}

mutation createPost($text: String!, $title: String!) {
  createPost(text: $text, title: $title) {
    ...post
  }
}
